AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A small scheduled task for pulling daily Toggl data into a JSON document and storing in S3.

Parameters:
  TogglEmail:
    Type: String
  TogglPassword:
    Type: String
  TogglWorkspaceId:
    Type: String

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  TogglDigest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
      Environment:
        Variables:
          TOGGL_EMAIL: !Ref TogglEmail
          TOGGL_PASSWORD: !Ref TogglPassword
          TOGGL_WORKSPACE_ID: !Ref TogglWorkspaceId